version: 2.1

workflows:
  version: 2
  test:
    jobs:
      - test-3-6
      - test-3-7
      - test-3-8
      - test-3-9
      - check-black
#      - flake8
      - mypy
      - publish:
          requires:
#            - flake8
            - mypy
            - check-black
            - test-3-6
            - test-3-7
            - test-3-8
            - test-3-9
          filters:
            branches:
              only: master
            tags:
              only: /^[0-9]+(\.[0-9]+)*$/

defaults: &defaults
  docker:
    - image: circleci/python:3.6
  environment:
    CRYPTOGRAPHY_DONT_BUILD_RUST: 1


cache-key: &cache-key
  deps-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}


restore_cache: &restore_cache
  restore_cache:
    name: "Restore cache"
    key: *cache-key

save_cache: &save_cache
  save_cache:
    key: *cache-key
    paths:
     - .venv

install_envo: &install_envo
  run:
    name: Install envo
    command: pip install envo==0.9.9.13

bootstrap: &bootstrap
  run:
    name: Bootstrap
    command: p.bootstrap
    shell: envo ci


jobs:
  flake8:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *install_envo
      - *bootstrap
      - run:
          name: Flake8
          command: p.flake
          shell: envo ci
      - *save_cache

  mypy:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *install_envo
      - *bootstrap
      - run:
          name: Mypy
          command: p.mypy
          shell: envo ci
      - *save_cache

  check-black:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *install_envo
      - *bootstrap
      - run:
          name: Black
          command: p.check_black
          shell: envo ci
      - *save_cache
  test-3-6:
    <<: *defaults
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout
      - *restore_cache
      - *install_envo
      - *bootstrap
      - run:
          name: Test
          command: p.test
          shell: envo ci
      - store_artifacts:
          path: htmlcov
          destination: coverage
      - store_test_results:
          path: test-results
      - *save_cache

  test-3-7:
    <<: *defaults
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - *restore_cache
      - *install_envo
      - *bootstrap
      - run:
          name: Test
          command: p.test
          shell: envo ci
      - store_artifacts:
          path: htmlcov
          destination: coverage
      - store_test_results:
          path: test-results
      - *save_cache

  test-3-8:
    <<: *defaults
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout
      - *restore_cache
      - *install_envo
      - *bootstrap
      - run:
          name: Test
          command: p.test
          shell: envo ci
      - store_artifacts:
          path: htmlcov
          destination: coverage
      - store_test_results:
          path: test-results
      - *save_cache

  test-3-9:
    <<: *defaults
    docker:
      - image: circleci/python:3.9

    steps:
      - checkout
      - *restore_cache
      - *install_envo
      - *bootstrap
      - run:
          name: Test
          command: p.test
          shell: envo ci
      - store_artifacts:
          path: htmlcov
          destination: coverage
      - store_test_results:
          path: test-results
      - *save_cache


  publish:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *install_envo
      - *bootstrap
      - run:
          name: Generate version
          command: p.generate_version
          shell: envo ci
      - run:
          name: Build
          command: p.build
          shell: envo ci
      - run:
          name: publish
          command: p.publish
          shell: envo ci
      - *save_cache
